### ISSUE TITLE
Who made an attempt on the emporer's life?

### ISSUE THREAD

**Issue by Geekwithahat** [Wyvinar/Observer#2]
Emperor Dalmzan is a seriously injured man in a suit of armour that hides every part of him, after a column of explosive fire destroyed half the emperor's palace.

**Comment by Wyvinar** [comment]
who:
- a lover
- a child
- a rebel
- an advisor/courtier

reasons:
- power
- change
- revenge

**Comment by Geekwithahat** [comment]
TODO: take this, pick two, then do it again to make it weird

**Comment by Wyvinar** [comment]
I forgot to add:
pure fuck off coincidence, some random dude wondered in at exactly the right time either trying to assassinate someone else, so he has a weapon on him, or the emporer was fucking around with a weapon and this dude managed to trigger it.
