### ISSUE TITLE
Runes used to see

### ISSUE THREAD

**Issue by Wyvinar** [Wyvinar/Observer#3]
what happens when the effects of a rune/Hyalloy are used to observe?

**Comment by Geekwithahat** [comment]
As in like, Camera runes?

**Comment by Geekwithahat** [comment]
Hang on I'm a dumbass, teleport and then you can see what's on the other side.

**Comment by Wyvinar** [comment]
nah, semi camera runes, teleporting light into your brain

**Comment by Geekwithahat** [comment]
I don't know, I mean I guess since they can defo teleport light they could teleport light into film?
